[project]
name = "ia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "click==8.4.1",
    "internetarchive==5.9.0",
    "pydantic==2.13.4",
    "python-dotenv>=1.2.2",
    "rich>=14.3.3",
    "wayback==0.5.0",
]

[project.scripts]
wb_coverage = "ia.wb_coverage:cli"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "ruff==0.15.16",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff.lint]
select = ["A", "E", "F", "I", "N", "Q", "S", "SIM", "T", "W"]
ignore = ["E501", "S101", "T201"]
