name: JavaScript Tests & Linting

on:
  push:
    branches: [main]
    paths:
      - 'astro.config.mjs'
      - 'content.config.ts'
      - 'eslint.config.js'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'public/**'
      - 'src/**'
      - 'tsconfig.json'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [main]
    paths:
      - 'astro.config.mjs'
      - 'content.config.ts'
      - 'eslint.config.js'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'public/**'
      - 'src/**'
      - 'tsconfig.json'
      - '.github/workflows/ci.yml'
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Install pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          version: 10

      - name: Setup Node
        uses: actions/setup-node@v7.0.0
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint and Check
        run: pnpm test
